"""
SentinelAI Manual Verification Engine
===================================
Provides utility functions for manual app analysis using data-driven intelligence:
Routes extracted application data to the new Intelligence Engine.
"""

from services.intelligence_engine import IntelligenceEngine
import services.gemini_service as gemini_service
import app_fetcher
from rapidfuzz import fuzz

def run_manual_analysis(data: dict) -> dict:
    app_name = data.get("app_name", "").strip()
    description = data.get("description", "").strip()
    developer = data.get("developer", "").strip()
    website = data.get("website", "").strip()
    apk_link = data.get("apk_link", "").strip()
    
    is_playstore_url = False
    playstore_data_found = False
    playstore_rating = 0.0
    playstore_downloads = "0"
    downloads_num = 0
    package_name = ""
    category = ""
    issues = []
    
    if apk_link and "play.google.com" in apk_link:
        is_playstore_url = True
        pkg_result = app_fetcher.extract_package_name(apk_link)
        if pkg_result.get("success"):
            package_name = pkg_result["package_name"]
            app_result = app_fetcher.fetch_app_details(package_name)
            if app_result.get("success"):
                details = app_result["data"]
                playstore_data_found = True
                
                # Merge Data Logic (User input takes priority if it exists)
                if not app_name and details.get("title"):
                    app_name = details["title"]
                
                if not description:
                    description = details.get("summary") or details.get("description", "")
                    
                if not website and details.get("url"):
                    website = details["url"]
                
                # Developer Logic
                ps_dev = details.get("developer", "")
                if developer and ps_dev:
                    # Check mismatch
                    score = fuzz.token_set_ratio(developer.lower(), ps_dev.lower())
                    if score < 80:
                        issues.append("User supplied developer differs from official Play Store developer.")
                elif not developer and ps_dev:
                    developer = ps_dev
                    
                playstore_rating = details.get("score", 0.0)
                playstore_downloads = details.get("installs", "0")
                downloads_num = details.get("real_installs") or int(str(playstore_downloads).replace("+", "").replace(",", "") or 0)
                category = details.get("genre", "")
    # Run through the intelligence engine
    result = IntelligenceEngine.analyze(
        app_name=app_name,
        developer=developer,
        website=website,
        description=description,
        package_name=package_name,
        rating=playstore_rating,
        downloads=downloads_num,
        category=category
    )
    
    if issues:
        result.setdefault("issues", []).extend(issues)
    
    if is_playstore_url:
        result["playstore_data_found"] = playstore_data_found
        result["playstore_rating"] = playstore_rating
        result["playstore_downloads"] = playstore_downloads
        # package_verified and developer_verified are generated by IntelligenceEngine
    elif apk_link and ".apk" in apk_link.lower():
        result.setdefault("reasons", []).append("Suspicious external APK download link provided")
        # Minor threat bump for external APK links outside Play Store
        result["threat_score"] = min(100, result["threat_score"] + 15)
        # Re-evaluate status if threat bumped
        if result["threat_score"] > 60 and result["trust_score"] < 40:
            result["status"] = "Suspicious"
    
    result["ai_report"] = gemini_service.generate_ai_report(result)
    result["success"] = True # Make sure success is true, wait run_manual_analysis doesn't return success typically?
    # IntelligenceEngine.analyze already returns "success": True inside it, we just add to it.
    
    result["developer"] = developer
    result["package_name"] = package_name
    
    return result
