"""
SentinelAI Enterprise - Demo Fixture Data
==========================================
Fictional organization: "Sentinel Demo Financial Services"
ALL DATA IS SYNTHETIC. Displayed with [DEMO] labels throughout.
Do not use these figures as real financial estimates.
"""
from datetime import datetime, date

DEMO_ORG_ID = "demo-sentinel-financial-services"

DEMO_ORG = {
    "_id": DEMO_ORG_ID,
    "name": "Sentinel Demo Financial Services [DEMO]",
    "industry": "Financial Services",
    "currency": "INR",
    "timezone": "Asia/Kolkata",
    "is_demo": True,
    "risk_appetite": {
        "exposure_limit_eal": 20_000_000,
        "exposure_limit_var95": 50_000_000,
        "currency": "INR",
    },
    "created_at": datetime(2026, 1, 1),
    "data_label": "[DEMO - SYNTHETIC DATA]",
}

DEMO_BUSINESS_UNITS = [
    {
        "_id": f"{DEMO_ORG_ID}-bu-retail",
        "org_id": DEMO_ORG_ID,
        "name": "Retail Banking & Investments [DEMO]",
        "description": "Manages retail customer accounts, investment products, and digital channels.",
        "owner_name": "Priya Sharma (Demo)",
        "annual_revenue_estimate": 500_000_000,
        "headcount": 120,
        "created_at": datetime(2026, 1, 1),
        "updated_at": datetime(2026, 1, 1),
    },
    {
        "_id": f"{DEMO_ORG_ID}-bu-corporate",
        "org_id": DEMO_ORG_ID,
        "name": "Corporate Treasury & Risk [DEMO]",
        "description": "Manages corporate treasury operations and enterprise risk.",
        "owner_name": "Arjun Mehta (Demo)",
        "annual_revenue_estimate": 300_000_000,
        "headcount": 45,
        "created_at": datetime(2026, 1, 1),
        "updated_at": datetime(2026, 1, 1),
    },
    {
        "_id": f"{DEMO_ORG_ID}-bu-it",
        "org_id": DEMO_ORG_ID,
        "name": "IT & Security Operations [DEMO]",
        "description": "Manages technology infrastructure and security operations.",
        "owner_name": "Kavitha Nair (Demo)",
        "annual_revenue_estimate": None,
        "headcount": 30,
        "created_at": datetime(2026, 1, 1),
        "updated_at": datetime(2026, 1, 1),
    },
]

_NOW = datetime(2026, 1, 1)

DEMO_ASSETS = [
    {"_id": f"{DEMO_ORG_ID}-ASSET-001", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-001",
     "name": "Core Banking System [DEMO]", "asset_type": "application",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-retail", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "restricted",
     "record_volume_estimate": 500_000, "criticality": "critical",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-002", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-002",
     "name": "Customer Database Primary [DEMO]", "asset_type": "database",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-retail", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "restricted",
     "record_volume_estimate": 250_000, "criticality": "critical",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-003", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-003",
     "name": "Internet Banking Portal [DEMO]", "asset_type": "application",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-retail", "environment": "production",
     "internet_exposed": True, "data_sensitivity": "confidential",
     "record_volume_estimate": None, "criticality": "high",
     "owner_name": "", "supporting_services": [], "dependencies": ["ASSET-001", "ASSET-002"],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-004", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-004",
     "name": "Mobile Banking App [DEMO]", "asset_type": "application",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-retail", "environment": "production",
     "internet_exposed": True, "data_sensitivity": "confidential",
     "record_volume_estimate": None, "criticality": "high",
     "owner_name": "", "supporting_services": [], "dependencies": ["ASSET-001", "ASSET-002"],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-005", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-005",
     "name": "Active Directory [DEMO]", "asset_type": "identity_system",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-it", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "confidential",
     "record_volume_estimate": 800, "criticality": "critical",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-006", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-006",
     "name": "Privileged Access Workstation [DEMO]", "asset_type": "endpoint",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-it", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "restricted",
     "record_volume_estimate": None, "criticality": "critical",
     "owner_name": "", "supporting_services": [], "dependencies": ["ASSET-005"],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-007", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-007",
     "name": "Application Server Cluster [DEMO]", "asset_type": "server",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-it", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "internal",
     "record_volume_estimate": None, "criticality": "high",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-008", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-008",
     "name": "Payment Gateway Integration [DEMO]", "asset_type": "saas_service",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-retail", "environment": "production",
     "internet_exposed": True, "data_sensitivity": "restricted",
     "record_volume_estimate": None, "criticality": "critical",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-009", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-009",
     "name": "SIEM & Log Management [DEMO]", "asset_type": "application",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-it", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "internal",
     "record_volume_estimate": None, "criticality": "medium",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-010", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-010",
     "name": "Backup and DR System [DEMO]", "asset_type": "server",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-it", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "confidential",
     "record_volume_estimate": None, "criticality": "high",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-011", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-011",
     "name": "Employee Laptops Pool (~150) [DEMO]", "asset_type": "endpoint",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-it", "environment": "production",
     "internet_exposed": True, "data_sensitivity": "internal",
     "record_volume_estimate": None, "criticality": "medium",
     "owner_name": "", "supporting_services": [], "dependencies": ["ASSET-005"],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-012", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-012",
     "name": "AWS S3 Document Archive [DEMO]", "asset_type": "cloud_resource",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-corporate", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "confidential",
     "record_volume_estimate": 50_000, "criticality": "medium",
     "owner_name": "", "supporting_services": [], "dependencies": [],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},

    {"_id": f"{DEMO_ORG_ID}-ASSET-013", "org_id": DEMO_ORG_ID, "internal_id": "ASSET-013",
     "name": "Treasury Management System [DEMO]", "asset_type": "application",
     "business_unit_id": f"{DEMO_ORG_ID}-bu-corporate", "environment": "production",
     "internet_exposed": False, "data_sensitivity": "restricted",
     "record_volume_estimate": None, "criticality": "high",
     "owner_name": "", "supporting_services": [], "dependencies": ["ASSET-005", "ASSET-002"],
     "source_system": "demo_fixture", "external_source_ids": {},
     "notes": "DEMO ASSET - synthetic", "created_at": _NOW, "updated_at": _NOW, "last_seen": _NOW},
]

DEMO_SERVICES = [
    {
        "_id": f"{DEMO_ORG_ID}-SVC-001",
        "org_id": DEMO_ORG_ID,
        "name": "Core Retail Banking Service [DEMO]",
        "description": "End-to-end retail banking including accounts, loans, and payments.",
        "business_unit_id": f"{DEMO_ORG_ID}-bu-retail",
        "owner_name": "Priya Sharma (Demo)",
        "supporting_asset_ids": ["ASSET-001", "ASSET-002", "ASSET-007", "ASSET-008", "ASSET-010"],
        "dependency_service_ids": [],
        "downtime_cost": {
            "cost_per_hour": 500_000,
            "basis": "DEMO ASSUMPTION: Analyst estimate. 0.1% of daily revenue + regulatory cost. Not validated.",
            "review_date": "2026-01-01",
            "currency": "INR",
        },
        "rto_hours": 4.0, "rpo_hours": 1.0, "importance": "critical",
        "created_at": _NOW, "updated_at": _NOW,
    },
    {
        "_id": f"{DEMO_ORG_ID}-SVC-002",
        "org_id": DEMO_ORG_ID,
        "name": "Digital Channels (Internet & Mobile) [DEMO]",
        "description": "Customer-facing internet banking portal and mobile banking app.",
        "business_unit_id": f"{DEMO_ORG_ID}-bu-retail",
        "owner_name": "Priya Sharma (Demo)",
        "supporting_asset_ids": ["ASSET-003", "ASSET-004", "ASSET-007"],
        "dependency_service_ids": [f"{DEMO_ORG_ID}-SVC-001"],
        "downtime_cost": {
            "cost_per_hour": 200_000,
            "basis": "DEMO ASSUMPTION: Analyst estimate. Customer churn + support cost. Not validated.",
            "review_date": "2026-01-01",
            "currency": "INR",
        },
        "rto_hours": 2.0, "rpo_hours": 0.5, "importance": "high",
        "created_at": _NOW, "updated_at": _NOW,
    },
    {
        "_id": f"{DEMO_ORG_ID}-SVC-003",
        "org_id": DEMO_ORG_ID,
        "name": "Corporate Treasury Operations [DEMO]",
        "description": "Treasury management, inter-bank settlements, and FX operations.",
        "business_unit_id": f"{DEMO_ORG_ID}-bu-corporate",
        "owner_name": "Arjun Mehta (Demo)",
        "supporting_asset_ids": ["ASSET-013", "ASSET-002", "ASSET-005"],
        "dependency_service_ids": [],
        "downtime_cost": {
            "cost_per_hour": 1_000_000,
            "basis": "DEMO ASSUMPTION: Settlement delays and counterparty penalty exposure. Analyst estimate.",
            "review_date": "2026-01-01",
            "currency": "INR",
        },
        "rto_hours": 1.0, "rpo_hours": 0.25, "importance": "critical",
        "created_at": _NOW, "updated_at": _NOW,
    },
]

DEMO_EVIDENCE = [
    {
        "_id": f"{DEMO_ORG_ID}-EVD-001",
        "org_id": DEMO_ORG_ID,
        "source_integration": "demo_vuln_scanner",
        "source_record_id": "CVE-2024-DEMO-001",
        "asset_id": "ASSET-003",
        "observation_time": datetime(2026, 8, 15),
        "ingestion_time": datetime(2026, 8, 15),
        "finding_type": "vulnerability",
        "severity": "high",
        "title": "Internet Banking Portal - Unpatched Web Framework [DEMO]",
        "description": "DEMO: Critical web framework vulnerability (CVSS 8.1) allowing authentication bypass.",
        "status": "open",
        "technical_identifiers": {"cve": "CVE-2024-DEMO-001", "cvss": 8.1},
        "import_batch_id": "demo_initial_load",
        "data_quality_note": "DEMO - synthetic vulnerability record",
        "affected_scenario_ids": [f"{DEMO_ORG_ID}-SCN-003"],
        "created_at": datetime(2026, 8, 15),
        "updated_at": datetime(2026, 8, 15),
    },
    {
        "_id": f"{DEMO_ORG_ID}-EVD-002",
        "org_id": DEMO_ORG_ID,
        "source_integration": "demo_iam_export",
        "source_record_id": "IAM-DEMO-ADMIN-001",
        "asset_id": "ASSET-005",
        "observation_time": datetime(2026, 9, 1),
        "ingestion_time": datetime(2026, 9, 1),
        "finding_type": "iam_risk",
        "severity": "critical",
        "title": "6 Admin Accounts Without MFA [DEMO]",
        "description": "DEMO: Six privileged admin accounts lack MFA. MFA coverage: 67% of 18 admin accounts.",
        "status": "open",
        "technical_identifiers": {"affected_accounts": 6, "total_admin_accounts": 18, "mfa_coverage_pct": 67},
        "import_batch_id": "demo_initial_load",
        "data_quality_note": "DEMO - synthetic IAM finding",
        "affected_scenario_ids": [f"{DEMO_ORG_ID}-SCN-002"],
        "created_at": datetime(2026, 9, 1),
        "updated_at": datetime(2026, 9, 1),
    },
    {
        "_id": f"{DEMO_ORG_ID}-EVD-003",
        "org_id": DEMO_ORG_ID,
        "source_integration": "demo_vuln_scanner",
        "source_record_id": "PATCH-DEMO-003",
        "asset_id": "ASSET-007",
        "observation_time": datetime(2026, 7, 20),
        "ingestion_time": datetime(2026, 7, 20),
        "finding_type": "vulnerability",
        "severity": "medium",
        "title": "App Server - 14 Patches Outstanding (>30 days) [DEMO]",
        "description": "DEMO: 14 security patches unapplied for more than 30 days on the application server cluster.",
        "status": "open",
        "technical_identifiers": {"outstanding_patches": 14, "max_age_days": 62},
        "import_batch_id": "demo_initial_load",
        "data_quality_note": "DEMO - synthetic vulnerability record",
        "affected_scenario_ids": [f"{DEMO_ORG_ID}-SCN-001"],
        "created_at": datetime(2026, 7, 20),
        "updated_at": datetime(2026, 7, 20),
    },
]

DEMO_SCENARIOS = [
    {
        "_id": f"{DEMO_ORG_ID}-SCN-001",
        "org_id": DEMO_ORG_ID,
        "name": "Ransomware - Core Service Interruption [DEMO]",
        "threat_event": "Ransomware deployment via phishing or unpatched vulnerability",
        "business_consequence": "Encryption of application servers and backup causing core banking outage",
        "affected_asset_ids": ["ASSET-001", "ASSET-007", "ASSET-010"],
        "affected_service_ids": [f"{DEMO_ORG_ID}-SVC-001"],
        "evidence_ids": [f"{DEMO_ORG_ID}-EVD-003"],
        "applicable_control_ids": [],
        "frequency_model": "analyst_estimate",
        "expected_incidents_per_year": 0.15,
        "frequency_basis": "DEMO ASSUMPTION: Indian BFSI ransomware frequency estimate from public threat reports 2023-2025. Analyst judgment. Not calibrated to this organization.",
        "loss_components": [
            {"name": "Service Downtime Loss", "description": "Revenue/operational cost during core banking outage",
             "min_inr": 2_000_000, "max_inr": 20_000_000, "most_likely_inr": 8_000_000,
             "basis": "DEMO ASSUMPTION: 4-40 hour outage x Rs5L/hour. Analyst estimate.",
             "conditional": False, "condition_description": "", "overlaps_with": []},
            {"name": "Incident Response & Investigation", "description": "Forensics, IR team, specialists",
             "min_inr": 500_000, "max_inr": 3_000_000, "most_likely_inr": 1_500_000,
             "basis": "DEMO ASSUMPTION: Industry benchmark mid-size BFSI IR. Analyst estimate.",
             "conditional": False, "condition_description": "", "overlaps_with": []},
            {"name": "System Recovery & Restoration", "description": "Rebuilding systems, restoring from backup",
             "min_inr": 500_000, "max_inr": 5_000_000, "most_likely_inr": 2_000_000,
             "basis": "DEMO ASSUMPTION: Analyst estimate for app server cluster rebuild.",
             "conditional": False, "condition_description": "", "overlaps_with": []},
        ],
        "model_version": "1.0",
        "assumption_review_date": "2026-01-01",
        "is_active": True,
        "notes": "DEMO SCENARIO. All loss figures are synthetic analyst assumptions, not validated predictions.",
        "created_at": _NOW, "updated_at": _NOW,
    },
    {
        "_id": f"{DEMO_ORG_ID}-SCN-002",
        "org_id": DEMO_ORG_ID,
        "name": "Privileged Account Compromise [DEMO]",
        "threat_event": "Attacker compromises admin account via credential theft or MFA absence",
        "business_consequence": "Unauthorized access to Active Directory, lateral movement, data access",
        "affected_asset_ids": ["ASSET-005", "ASSET-006", "ASSET-001", "ASSET-002"],
        "affected_service_ids": [],
        "evidence_ids": [f"{DEMO_ORG_ID}-EVD-002"],
        "applicable_control_ids": [],
        "frequency_model": "analyst_estimate",
        "expected_incidents_per_year": 0.20,
        "frequency_basis": "DEMO ASSUMPTION: Elevated by EVD-002 (6 admin accounts without MFA). Analyst estimate.",
        "loss_components": [
            {"name": "Unauthorized Data Access / Exfiltration", "description": "Loss from data accessed during compromise",
             "min_inr": 1_000_000, "max_inr": 15_000_000, "most_likely_inr": 5_000_000,
             "basis": "DEMO ASSUMPTION: Depends on dwell time and data accessed. Analyst range.",
             "conditional": False, "condition_description": "", "overlaps_with": []},
            {"name": "Incident Response", "description": "Detection, containment, investigation",
             "min_inr": 300_000, "max_inr": 2_000_000, "most_likely_inr": 800_000,
             "basis": "DEMO ASSUMPTION: Analyst estimate for identity incident IR scope.",
             "conditional": False, "condition_description": "", "overlaps_with": []},
        ],
        "model_version": "1.0",
        "assumption_review_date": "2026-01-01",
        "is_active": True,
        "notes": "DEMO SCENARIO. All loss figures are synthetic analyst assumptions.",
        "created_at": _NOW, "updated_at": _NOW,
    },
    {
        "_id": f"{DEMO_ORG_ID}-SCN-003",
        "org_id": DEMO_ORG_ID,
        "name": "Customer Data Breach [DEMO]",
        "threat_event": "Exploitation of web vulnerability to extract customer PII/financial data",
        "business_consequence": "Exfiltration of customer records, CERT-In reporting obligation, regulatory scrutiny",
        "affected_asset_ids": ["ASSET-002", "ASSET-003", "ASSET-004"],
        "affected_service_ids": [f"{DEMO_ORG_ID}-SVC-002"],
        "evidence_ids": [f"{DEMO_ORG_ID}-EVD-001"],
        "applicable_control_ids": [],
        "frequency_model": "analyst_estimate",
        "expected_incidents_per_year": 0.10,
        "frequency_basis": "DEMO ASSUMPTION: Elevated by EVD-001 unpatched web portal CVSS 8.1. Analyst estimate.",
        "loss_components": [
            {"name": "Breach Notification & Customer Communication", "description": "CERT-In notification, customer alerts, credit monitoring",
             "min_inr": 500_000, "max_inr": 3_000_000, "most_likely_inr": 1_200_000,
             "basis": "DEMO ASSUMPTION: CERT-In 6-hour reporting + customer comms. Analyst estimate.",
             "conditional": False, "condition_description": "", "overlaps_with": []},
            {"name": "Regulatory Consequence (Conditional)", "description": "RBI/SEBI penalty or remediation directive costs",
             "min_inr": 1_000_000, "max_inr": 10_000_000, "most_likely_inr": 3_000_000,
             "basis": "DEMO ASSUMPTION: Conditional on breach scale and regulatory action. Indian BFSI precedent.",
             "conditional": True,
             "condition_description": "Applies if breach involves >10,000 customer records or triggers formal regulatory action",
             "overlaps_with": []},
            {"name": "Incident Response", "description": "Forensics and investigation",
             "min_inr": 400_000, "max_inr": 2_500_000, "most_likely_inr": 1_000_000,
             "basis": "DEMO ASSUMPTION: Analyst estimate for web breach IR scope.",
             "conditional": False, "condition_description": "", "overlaps_with": []},
        ],
        "model_version": "1.0",
        "assumption_review_date": "2026-01-01",
        "is_active": True,
        "notes": "DEMO SCENARIO. Penalty assumptions are conditional and depend on regulatory determination.",
        "created_at": _NOW, "updated_at": _NOW,
    },
]


def get_demo_fixture_bundle() -> dict:
    """Returns all demo fixtures in a single dictionary without requiring database connection."""
    return {
        "org_id": DEMO_ORG_ID,
        "org": DEMO_ORG,
        "business_units": DEMO_BUSINESS_UNITS,
        "assets": DEMO_ASSETS,
        "services": DEMO_SERVICES,
        "evidence": DEMO_EVIDENCE,
        "scenarios": DEMO_SCENARIOS,
    }
