const API_BASE_URL = import.meta.env.VITE_API_URL || "http://161.118.177.73:8000";

// In-memory scan data store with event-driven updates.
// Clean interface so it can be replaced with a real backend later.

let scans = [];
let dashboardStats = {
  total_scans: 0,
  safe_apps: 0,
  medium_risk: 0,
  high_risk: 0
};
let listeners = [];
let isInitialized = false;

function generateId() {
  return 'scan_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
}

function notify() {
  listeners.forEach(fn => fn(getState()));
}

export async function fetchInitialData() {
  try {
    const historyRes = await fetch(`${API_BASE_URL}/scan-history`);
    if (historyRes.ok) {
      const rawHistory = await historyRes.json();
      scans = rawHistory.map(row => {
        let rawData = {};
        if (row.raw_data) {
          try {
            rawData = JSON.parse(row.raw_data);
          } catch (e) {
            console.error("Failed to parse raw_data", e);
          }
        }
        
        // Manual verification puts analysis properties at root. Play Store puts them in "analysis".
        const analysis = rawData.analysis || rawData;
        const appDetails = rawData.app_details || {};
        
        return {
          id: row.scan_uuid,
          scan_uuid: row.scan_uuid,
          type: row.scan_type === 'Play Store' ? 'playstore' : (row.scan_type === 'Manual Analysis' ? 'manual' : (row.scan_type === 'APK Scan' ? 'apk' : 'unknown')),
          verificationStatus: row.status,
          appName: row.app_name,
          developer: rawData.developer || appDetails.developer || 'Unknown',
          timestamp: row.timestamp,
          trustScore: row.trust_score,
          threatScore: row.threat_score,
          confidenceScore: row.confidence_score,
          status: row.status,
          
          // Extracted rich data
          aiVerdict: (() => {
            const rawVerdict = analysis.ai_report || rawData.ai_report;
            if (!rawVerdict) return 'AI assessment unavailable';
            if (typeof rawVerdict === 'string') {
              try {
                return JSON.parse(rawVerdict.replace(/```json/g, '').replace(/```/g, '').trim());
              } catch (e) {
                return rawVerdict;
              }
            }
            return rawVerdict;
          })(),
          detectedIssues: analysis.issues?.map(i => ({ severity: row.threat_score >= 70 ? 'High' : 'Medium', title: 'Issue', description: i })) || rawData.issues?.map(i => ({ severity: row.threat_score >= 70 ? 'High' : 'Medium', title: 'Issue', description: i })) || [],
          recommendations: [], // Fallback or could map if generated by backend
          permissions: [], 
          summary: `Analysis completed with threat score: ${row.threat_score}`,
          
          // Evidence construction
          evidence: [
             { type: 'metric', label: 'Trust Score', value: `${row.trust_score}/100` },
             { type: 'metric', label: 'Threat Score', value: `${row.threat_score}/100` },
             ...(analysis.trust_signals || rawData.trust_signals || []).map(s => ({ type: 'text', label: 'Verified Signal', value: s }))
          ],
          
          // Play Store specific UI data
          playstoreDataFound: !!appDetails.title || rawData.playstore_data_found,
          playstoreRating: appDetails.score || rawData.playstore_rating || 'N/A',
          playstoreDownloads: appDetails.installs || rawData.playstore_downloads || 'N/A',
          packageName: rawData.package_name || 'N/A'
        };
      });
    }
    
    const statsRes = await fetch(`${API_BASE_URL}/dashboard-stats`);
    if (statsRes.ok) {
      dashboardStats = await statsRes.json();
    }
    
    isInitialized = true;
    notify();
  } catch (error) {
    console.error('Error fetching initial data:', error);
  }
}

// Kick off initial fetch immediately
fetchInitialData();

export function addScan(result) {
  // Optimistically add to local state so navigation works immediately
  scans = [result, ...scans];
  if (result.type === 'playstore' || result.type === 'manual') {
    fetchInitialData();
  } else {
    notify(); // just notify listeners for mock scans so UI updates
  }
  return result;
}

export function getScans() {
  return [...scans];
}

export function getScanById(id) {
  return scans.find(s => s.id === id || s.scan_uuid === id) || null;
}

export function getStats() {
  return { 
    total: dashboardStats.total_scans || 0, 
    safe: dashboardStats.safe_apps || 0,
    medium: dashboardStats.medium_risk || 0, 
    high: dashboardStats.high_risk || 0,
    highRisk: dashboardStats.high_risk || 0,
    critical: dashboardStats.high_risk || 0, // Fallbacks for existing UI
    low: dashboardStats.safe_apps || 0,
    avgScore: 50 // Mock for now if needed by UI
  };
}

export function getFlaggedApps() {
  return scans.filter(s => ['Needs Review', 'Suspicious', 'Potential Impersonation', 'High Risk Fraud', 'Critical Threat', 'High', 'Critical'].includes(s.status));
}

export function getThreatIntelMetrics() {
  return { 
    highRisk: dashboardStats.high_risk || 0, 
    mediumRisk: dashboardStats.medium_risk || 0, 
    newlyDetected: 0, 
    topThreats: [], 
    totalEvaluated: dashboardStats.total_scans || 0 
  };
}

export function getHistory() {
  return [...scans];
}

export function subscribe(callback) {
  listeners.push(callback);
  return () => {
    listeners = listeners.filter(fn => fn !== callback);
  };
}

export function getState() {
  return {
    scans: getScans(),
    stats: getStats(),
    flaggedApps: getFlaggedApps(),
    threatMetrics: getThreatIntelMetrics(),
    history: getHistory(),
  };
}
